// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SISChamados.InfraStructure.Data;
using System;

namespace SISChamados.InfraStructure.Migrations
{
    [DbContext(typeof(ChamadoContexto))]
    [Migration("20190409163915_AdicionaClasseChamado")]
    partial class AdicionaClasseChamado
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SISChamados.ApplicationCore.Entity.Chamado", b =>
                {
                    b.Property<int>("ChamadoID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.Property<DateTime>("DtFim");

                    b.Property<DateTime>("DtInicio");

                    b.Property<string>("Solucao");

                    b.Property<int>("UsuarioID");

                    b.HasKey("ChamadoID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("TbChamado");
                });

            modelBuilder.Entity("SISChamados.ApplicationCore.Entity.Usuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CPF");

                    b.Property<string>("Email");

                    b.Property<string>("NomeUsuario");

                    b.Property<string>("Telefone");

                    b.HasKey("UsuarioID");

                    b.ToTable("TbUsuario");
                });

            modelBuilder.Entity("SISChamados.ApplicationCore.Entity.Chamado", b =>
                {
                    b.HasOne("SISChamados.ApplicationCore.Entity.Usuario", "Usuario")
                        .WithMany("Chamados")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
